version: '3'
services:
  client:
    cap_add:
      - NET_ADMIN
    depends_on:
      - server
    env_file:
      - base.env
    environment:
      - ICE_ROLES=client:tcp:8080
    image: icemicro/examples-nginx-client:latest
  server:
    cap_add:
      - NET_ADMIN
    env_file:
      - base.env
    environment:
      - ICE_ROLES=server:tcp:8080
    image: icemicro/examples-nginx-server:latest
    ports:
      - 8080:8080
